// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parsimony.proto

#ifndef PROTOBUF_INCLUDED_parsimony_2eproto
#define PROTOBUF_INCLUDED_parsimony_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_parsimony_2eproto 

namespace protobuf_parsimony_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_parsimony_2eproto
namespace Parsimony {
class condensed_node;
class condensed_nodeDefaultTypeInternal;
extern condensed_nodeDefaultTypeInternal _condensed_node_default_instance_;
class data;
class dataDefaultTypeInternal;
extern dataDefaultTypeInternal _data_default_instance_;
class mut;
class mutDefaultTypeInternal;
extern mutDefaultTypeInternal _mut_default_instance_;
class mutation_list;
class mutation_listDefaultTypeInternal;
extern mutation_listDefaultTypeInternal _mutation_list_default_instance_;
class node_metadata;
class node_metadataDefaultTypeInternal;
extern node_metadataDefaultTypeInternal _node_metadata_default_instance_;
}  // namespace Parsimony
namespace google {
namespace protobuf {
template<> ::Parsimony::condensed_node* Arena::CreateMaybeMessage<::Parsimony::condensed_node>(Arena*);
template<> ::Parsimony::data* Arena::CreateMaybeMessage<::Parsimony::data>(Arena*);
template<> ::Parsimony::mut* Arena::CreateMaybeMessage<::Parsimony::mut>(Arena*);
template<> ::Parsimony::mutation_list* Arena::CreateMaybeMessage<::Parsimony::mutation_list>(Arena*);
template<> ::Parsimony::node_metadata* Arena::CreateMaybeMessage<::Parsimony::node_metadata>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Parsimony {

// ===================================================================

class mut : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parsimony.mut) */ {
 public:
  mut();
  virtual ~mut();

  mut(const mut& from);

  inline mut& operator=(const mut& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  mut(mut&& from) noexcept
    : mut() {
    *this = ::std::move(from);
  }

  inline mut& operator=(mut&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const mut& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mut* internal_default_instance() {
    return reinterpret_cast<const mut*>(
               &_mut_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(mut* other);
  friend void swap(mut& a, mut& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline mut* New() const final {
    return CreateMaybeMessage<mut>(NULL);
  }

  mut* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<mut>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const mut& from);
  void MergeFrom(const mut& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 mut_nuc = 4;
  int mut_nuc_size() const;
  void clear_mut_nuc();
  static const int kMutNucFieldNumber = 4;
  ::google::protobuf::int32 mut_nuc(int index) const;
  void set_mut_nuc(int index, ::google::protobuf::int32 value);
  void add_mut_nuc(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      mut_nuc() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_mut_nuc();

  // string chromosome = 5;
  void clear_chromosome();
  static const int kChromosomeFieldNumber = 5;
  const ::std::string& chromosome() const;
  void set_chromosome(const ::std::string& value);
  #if LANG_CXX11
  void set_chromosome(::std::string&& value);
  #endif
  void set_chromosome(const char* value);
  void set_chromosome(const char* value, size_t size);
  ::std::string* mutable_chromosome();
  ::std::string* release_chromosome();
  void set_allocated_chromosome(::std::string* chromosome);

  // int32 position = 1;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  ::google::protobuf::int32 position() const;
  void set_position(::google::protobuf::int32 value);

  // int32 ref_nuc = 2;
  void clear_ref_nuc();
  static const int kRefNucFieldNumber = 2;
  ::google::protobuf::int32 ref_nuc() const;
  void set_ref_nuc(::google::protobuf::int32 value);

  // int32 par_nuc = 3;
  void clear_par_nuc();
  static const int kParNucFieldNumber = 3;
  ::google::protobuf::int32 par_nuc() const;
  void set_par_nuc(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Parsimony.mut)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > mut_nuc_;
  mutable int _mut_nuc_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr chromosome_;
  ::google::protobuf::int32 position_;
  ::google::protobuf::int32 ref_nuc_;
  ::google::protobuf::int32 par_nuc_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_parsimony_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class mutation_list : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parsimony.mutation_list) */ {
 public:
  mutation_list();
  virtual ~mutation_list();

  mutation_list(const mutation_list& from);

  inline mutation_list& operator=(const mutation_list& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  mutation_list(mutation_list&& from) noexcept
    : mutation_list() {
    *this = ::std::move(from);
  }

  inline mutation_list& operator=(mutation_list&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const mutation_list& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mutation_list* internal_default_instance() {
    return reinterpret_cast<const mutation_list*>(
               &_mutation_list_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(mutation_list* other);
  friend void swap(mutation_list& a, mutation_list& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline mutation_list* New() const final {
    return CreateMaybeMessage<mutation_list>(NULL);
  }

  mutation_list* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<mutation_list>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const mutation_list& from);
  void MergeFrom(const mutation_list& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mutation_list* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parsimony.mut mutation = 1;
  int mutation_size() const;
  void clear_mutation();
  static const int kMutationFieldNumber = 1;
  ::Parsimony::mut* mutable_mutation(int index);
  ::google::protobuf::RepeatedPtrField< ::Parsimony::mut >*
      mutable_mutation();
  const ::Parsimony::mut& mutation(int index) const;
  ::Parsimony::mut* add_mutation();
  const ::google::protobuf::RepeatedPtrField< ::Parsimony::mut >&
      mutation() const;

  // @@protoc_insertion_point(class_scope:Parsimony.mutation_list)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Parsimony::mut > mutation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_parsimony_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class condensed_node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parsimony.condensed_node) */ {
 public:
  condensed_node();
  virtual ~condensed_node();

  condensed_node(const condensed_node& from);

  inline condensed_node& operator=(const condensed_node& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  condensed_node(condensed_node&& from) noexcept
    : condensed_node() {
    *this = ::std::move(from);
  }

  inline condensed_node& operator=(condensed_node&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const condensed_node& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const condensed_node* internal_default_instance() {
    return reinterpret_cast<const condensed_node*>(
               &_condensed_node_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(condensed_node* other);
  friend void swap(condensed_node& a, condensed_node& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline condensed_node* New() const final {
    return CreateMaybeMessage<condensed_node>(NULL);
  }

  condensed_node* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<condensed_node>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const condensed_node& from);
  void MergeFrom(const condensed_node& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(condensed_node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string condensed_leaves = 2;
  int condensed_leaves_size() const;
  void clear_condensed_leaves();
  static const int kCondensedLeavesFieldNumber = 2;
  const ::std::string& condensed_leaves(int index) const;
  ::std::string* mutable_condensed_leaves(int index);
  void set_condensed_leaves(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_condensed_leaves(int index, ::std::string&& value);
  #endif
  void set_condensed_leaves(int index, const char* value);
  void set_condensed_leaves(int index, const char* value, size_t size);
  ::std::string* add_condensed_leaves();
  void add_condensed_leaves(const ::std::string& value);
  #if LANG_CXX11
  void add_condensed_leaves(::std::string&& value);
  #endif
  void add_condensed_leaves(const char* value);
  void add_condensed_leaves(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& condensed_leaves() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_condensed_leaves();

  // string node_name = 1;
  void clear_node_name();
  static const int kNodeNameFieldNumber = 1;
  const ::std::string& node_name() const;
  void set_node_name(const ::std::string& value);
  #if LANG_CXX11
  void set_node_name(::std::string&& value);
  #endif
  void set_node_name(const char* value);
  void set_node_name(const char* value, size_t size);
  ::std::string* mutable_node_name();
  ::std::string* release_node_name();
  void set_allocated_node_name(::std::string* node_name);

  // @@protoc_insertion_point(class_scope:Parsimony.condensed_node)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> condensed_leaves_;
  ::google::protobuf::internal::ArenaStringPtr node_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_parsimony_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class node_metadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parsimony.node_metadata) */ {
 public:
  node_metadata();
  virtual ~node_metadata();

  node_metadata(const node_metadata& from);

  inline node_metadata& operator=(const node_metadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  node_metadata(node_metadata&& from) noexcept
    : node_metadata() {
    *this = ::std::move(from);
  }

  inline node_metadata& operator=(node_metadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const node_metadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const node_metadata* internal_default_instance() {
    return reinterpret_cast<const node_metadata*>(
               &_node_metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(node_metadata* other);
  friend void swap(node_metadata& a, node_metadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline node_metadata* New() const final {
    return CreateMaybeMessage<node_metadata>(NULL);
  }

  node_metadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<node_metadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const node_metadata& from);
  void MergeFrom(const node_metadata& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(node_metadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string clade_annotations = 1;
  int clade_annotations_size() const;
  void clear_clade_annotations();
  static const int kCladeAnnotationsFieldNumber = 1;
  const ::std::string& clade_annotations(int index) const;
  ::std::string* mutable_clade_annotations(int index);
  void set_clade_annotations(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_clade_annotations(int index, ::std::string&& value);
  #endif
  void set_clade_annotations(int index, const char* value);
  void set_clade_annotations(int index, const char* value, size_t size);
  ::std::string* add_clade_annotations();
  void add_clade_annotations(const ::std::string& value);
  #if LANG_CXX11
  void add_clade_annotations(::std::string&& value);
  #endif
  void add_clade_annotations(const char* value);
  void add_clade_annotations(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& clade_annotations() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_clade_annotations();

  // @@protoc_insertion_point(class_scope:Parsimony.node_metadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> clade_annotations_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_parsimony_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parsimony.data) */ {
 public:
  data();
  virtual ~data();

  data(const data& from);

  inline data& operator=(const data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  data(data&& from) noexcept
    : data() {
    *this = ::std::move(from);
  }

  inline data& operator=(data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const data* internal_default_instance() {
    return reinterpret_cast<const data*>(
               &_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(data* other);
  friend void swap(data& a, data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline data* New() const final {
    return CreateMaybeMessage<data>(NULL);
  }

  data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const data& from);
  void MergeFrom(const data& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parsimony.mutation_list node_mutations = 2;
  int node_mutations_size() const;
  void clear_node_mutations();
  static const int kNodeMutationsFieldNumber = 2;
  ::Parsimony::mutation_list* mutable_node_mutations(int index);
  ::google::protobuf::RepeatedPtrField< ::Parsimony::mutation_list >*
      mutable_node_mutations();
  const ::Parsimony::mutation_list& node_mutations(int index) const;
  ::Parsimony::mutation_list* add_node_mutations();
  const ::google::protobuf::RepeatedPtrField< ::Parsimony::mutation_list >&
      node_mutations() const;

  // repeated .Parsimony.condensed_node condensed_nodes = 3;
  int condensed_nodes_size() const;
  void clear_condensed_nodes();
  static const int kCondensedNodesFieldNumber = 3;
  ::Parsimony::condensed_node* mutable_condensed_nodes(int index);
  ::google::protobuf::RepeatedPtrField< ::Parsimony::condensed_node >*
      mutable_condensed_nodes();
  const ::Parsimony::condensed_node& condensed_nodes(int index) const;
  ::Parsimony::condensed_node* add_condensed_nodes();
  const ::google::protobuf::RepeatedPtrField< ::Parsimony::condensed_node >&
      condensed_nodes() const;

  // repeated .Parsimony.node_metadata metadata = 4;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 4;
  ::Parsimony::node_metadata* mutable_metadata(int index);
  ::google::protobuf::RepeatedPtrField< ::Parsimony::node_metadata >*
      mutable_metadata();
  const ::Parsimony::node_metadata& metadata(int index) const;
  ::Parsimony::node_metadata* add_metadata();
  const ::google::protobuf::RepeatedPtrField< ::Parsimony::node_metadata >&
      metadata() const;

  // string newick = 1;
  void clear_newick();
  static const int kNewickFieldNumber = 1;
  const ::std::string& newick() const;
  void set_newick(const ::std::string& value);
  #if LANG_CXX11
  void set_newick(::std::string&& value);
  #endif
  void set_newick(const char* value);
  void set_newick(const char* value, size_t size);
  ::std::string* mutable_newick();
  ::std::string* release_newick();
  void set_allocated_newick(::std::string* newick);

  // @@protoc_insertion_point(class_scope:Parsimony.data)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Parsimony::mutation_list > node_mutations_;
  ::google::protobuf::RepeatedPtrField< ::Parsimony::condensed_node > condensed_nodes_;
  ::google::protobuf::RepeatedPtrField< ::Parsimony::node_metadata > metadata_;
  ::google::protobuf::internal::ArenaStringPtr newick_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_parsimony_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// mut

// int32 position = 1;
inline void mut::clear_position() {
  position_ = 0;
}
inline ::google::protobuf::int32 mut::position() const {
  // @@protoc_insertion_point(field_get:Parsimony.mut.position)
  return position_;
}
inline void mut::set_position(::google::protobuf::int32 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:Parsimony.mut.position)
}

// int32 ref_nuc = 2;
inline void mut::clear_ref_nuc() {
  ref_nuc_ = 0;
}
inline ::google::protobuf::int32 mut::ref_nuc() const {
  // @@protoc_insertion_point(field_get:Parsimony.mut.ref_nuc)
  return ref_nuc_;
}
inline void mut::set_ref_nuc(::google::protobuf::int32 value) {
  
  ref_nuc_ = value;
  // @@protoc_insertion_point(field_set:Parsimony.mut.ref_nuc)
}

// int32 par_nuc = 3;
inline void mut::clear_par_nuc() {
  par_nuc_ = 0;
}
inline ::google::protobuf::int32 mut::par_nuc() const {
  // @@protoc_insertion_point(field_get:Parsimony.mut.par_nuc)
  return par_nuc_;
}
inline void mut::set_par_nuc(::google::protobuf::int32 value) {
  
  par_nuc_ = value;
  // @@protoc_insertion_point(field_set:Parsimony.mut.par_nuc)
}

// repeated int32 mut_nuc = 4;
inline int mut::mut_nuc_size() const {
  return mut_nuc_.size();
}
inline void mut::clear_mut_nuc() {
  mut_nuc_.Clear();
}
inline ::google::protobuf::int32 mut::mut_nuc(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.mut.mut_nuc)
  return mut_nuc_.Get(index);
}
inline void mut::set_mut_nuc(int index, ::google::protobuf::int32 value) {
  mut_nuc_.Set(index, value);
  // @@protoc_insertion_point(field_set:Parsimony.mut.mut_nuc)
}
inline void mut::add_mut_nuc(::google::protobuf::int32 value) {
  mut_nuc_.Add(value);
  // @@protoc_insertion_point(field_add:Parsimony.mut.mut_nuc)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
mut::mut_nuc() const {
  // @@protoc_insertion_point(field_list:Parsimony.mut.mut_nuc)
  return mut_nuc_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
mut::mutable_mut_nuc() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.mut.mut_nuc)
  return &mut_nuc_;
}

// string chromosome = 5;
inline void mut::clear_chromosome() {
  chromosome_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& mut::chromosome() const {
  // @@protoc_insertion_point(field_get:Parsimony.mut.chromosome)
  return chromosome_.GetNoArena();
}
inline void mut::set_chromosome(const ::std::string& value) {
  
  chromosome_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Parsimony.mut.chromosome)
}
#if LANG_CXX11
inline void mut::set_chromosome(::std::string&& value) {
  
  chromosome_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Parsimony.mut.chromosome)
}
#endif
inline void mut::set_chromosome(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  chromosome_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Parsimony.mut.chromosome)
}
inline void mut::set_chromosome(const char* value, size_t size) {
  
  chromosome_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Parsimony.mut.chromosome)
}
inline ::std::string* mut::mutable_chromosome() {
  
  // @@protoc_insertion_point(field_mutable:Parsimony.mut.chromosome)
  return chromosome_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* mut::release_chromosome() {
  // @@protoc_insertion_point(field_release:Parsimony.mut.chromosome)
  
  return chromosome_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void mut::set_allocated_chromosome(::std::string* chromosome) {
  if (chromosome != NULL) {
    
  } else {
    
  }
  chromosome_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), chromosome);
  // @@protoc_insertion_point(field_set_allocated:Parsimony.mut.chromosome)
}

// -------------------------------------------------------------------

// mutation_list

// repeated .Parsimony.mut mutation = 1;
inline int mutation_list::mutation_size() const {
  return mutation_.size();
}
inline void mutation_list::clear_mutation() {
  mutation_.Clear();
}
inline ::Parsimony::mut* mutation_list::mutable_mutation(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.mutation_list.mutation)
  return mutation_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parsimony::mut >*
mutation_list::mutable_mutation() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.mutation_list.mutation)
  return &mutation_;
}
inline const ::Parsimony::mut& mutation_list::mutation(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.mutation_list.mutation)
  return mutation_.Get(index);
}
inline ::Parsimony::mut* mutation_list::add_mutation() {
  // @@protoc_insertion_point(field_add:Parsimony.mutation_list.mutation)
  return mutation_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parsimony::mut >&
mutation_list::mutation() const {
  // @@protoc_insertion_point(field_list:Parsimony.mutation_list.mutation)
  return mutation_;
}

// -------------------------------------------------------------------

// condensed_node

// string node_name = 1;
inline void condensed_node::clear_node_name() {
  node_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& condensed_node::node_name() const {
  // @@protoc_insertion_point(field_get:Parsimony.condensed_node.node_name)
  return node_name_.GetNoArena();
}
inline void condensed_node::set_node_name(const ::std::string& value) {
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Parsimony.condensed_node.node_name)
}
#if LANG_CXX11
inline void condensed_node::set_node_name(::std::string&& value) {
  
  node_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Parsimony.condensed_node.node_name)
}
#endif
inline void condensed_node::set_node_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Parsimony.condensed_node.node_name)
}
inline void condensed_node::set_node_name(const char* value, size_t size) {
  
  node_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Parsimony.condensed_node.node_name)
}
inline ::std::string* condensed_node::mutable_node_name() {
  
  // @@protoc_insertion_point(field_mutable:Parsimony.condensed_node.node_name)
  return node_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* condensed_node::release_node_name() {
  // @@protoc_insertion_point(field_release:Parsimony.condensed_node.node_name)
  
  return node_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void condensed_node::set_allocated_node_name(::std::string* node_name) {
  if (node_name != NULL) {
    
  } else {
    
  }
  node_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), node_name);
  // @@protoc_insertion_point(field_set_allocated:Parsimony.condensed_node.node_name)
}

// repeated string condensed_leaves = 2;
inline int condensed_node::condensed_leaves_size() const {
  return condensed_leaves_.size();
}
inline void condensed_node::clear_condensed_leaves() {
  condensed_leaves_.Clear();
}
inline const ::std::string& condensed_node::condensed_leaves(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.condensed_node.condensed_leaves)
  return condensed_leaves_.Get(index);
}
inline ::std::string* condensed_node::mutable_condensed_leaves(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.condensed_node.condensed_leaves)
  return condensed_leaves_.Mutable(index);
}
inline void condensed_node::set_condensed_leaves(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Parsimony.condensed_node.condensed_leaves)
  condensed_leaves_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void condensed_node::set_condensed_leaves(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Parsimony.condensed_node.condensed_leaves)
  condensed_leaves_.Mutable(index)->assign(std::move(value));
}
#endif
inline void condensed_node::set_condensed_leaves(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  condensed_leaves_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Parsimony.condensed_node.condensed_leaves)
}
inline void condensed_node::set_condensed_leaves(int index, const char* value, size_t size) {
  condensed_leaves_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Parsimony.condensed_node.condensed_leaves)
}
inline ::std::string* condensed_node::add_condensed_leaves() {
  // @@protoc_insertion_point(field_add_mutable:Parsimony.condensed_node.condensed_leaves)
  return condensed_leaves_.Add();
}
inline void condensed_node::add_condensed_leaves(const ::std::string& value) {
  condensed_leaves_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Parsimony.condensed_node.condensed_leaves)
}
#if LANG_CXX11
inline void condensed_node::add_condensed_leaves(::std::string&& value) {
  condensed_leaves_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Parsimony.condensed_node.condensed_leaves)
}
#endif
inline void condensed_node::add_condensed_leaves(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  condensed_leaves_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Parsimony.condensed_node.condensed_leaves)
}
inline void condensed_node::add_condensed_leaves(const char* value, size_t size) {
  condensed_leaves_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Parsimony.condensed_node.condensed_leaves)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
condensed_node::condensed_leaves() const {
  // @@protoc_insertion_point(field_list:Parsimony.condensed_node.condensed_leaves)
  return condensed_leaves_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
condensed_node::mutable_condensed_leaves() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.condensed_node.condensed_leaves)
  return &condensed_leaves_;
}

// -------------------------------------------------------------------

// node_metadata

// repeated string clade_annotations = 1;
inline int node_metadata::clade_annotations_size() const {
  return clade_annotations_.size();
}
inline void node_metadata::clear_clade_annotations() {
  clade_annotations_.Clear();
}
inline const ::std::string& node_metadata::clade_annotations(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.node_metadata.clade_annotations)
  return clade_annotations_.Get(index);
}
inline ::std::string* node_metadata::mutable_clade_annotations(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.node_metadata.clade_annotations)
  return clade_annotations_.Mutable(index);
}
inline void node_metadata::set_clade_annotations(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Parsimony.node_metadata.clade_annotations)
  clade_annotations_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void node_metadata::set_clade_annotations(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:Parsimony.node_metadata.clade_annotations)
  clade_annotations_.Mutable(index)->assign(std::move(value));
}
#endif
inline void node_metadata::set_clade_annotations(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  clade_annotations_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Parsimony.node_metadata.clade_annotations)
}
inline void node_metadata::set_clade_annotations(int index, const char* value, size_t size) {
  clade_annotations_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Parsimony.node_metadata.clade_annotations)
}
inline ::std::string* node_metadata::add_clade_annotations() {
  // @@protoc_insertion_point(field_add_mutable:Parsimony.node_metadata.clade_annotations)
  return clade_annotations_.Add();
}
inline void node_metadata::add_clade_annotations(const ::std::string& value) {
  clade_annotations_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Parsimony.node_metadata.clade_annotations)
}
#if LANG_CXX11
inline void node_metadata::add_clade_annotations(::std::string&& value) {
  clade_annotations_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Parsimony.node_metadata.clade_annotations)
}
#endif
inline void node_metadata::add_clade_annotations(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  clade_annotations_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Parsimony.node_metadata.clade_annotations)
}
inline void node_metadata::add_clade_annotations(const char* value, size_t size) {
  clade_annotations_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Parsimony.node_metadata.clade_annotations)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
node_metadata::clade_annotations() const {
  // @@protoc_insertion_point(field_list:Parsimony.node_metadata.clade_annotations)
  return clade_annotations_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
node_metadata::mutable_clade_annotations() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.node_metadata.clade_annotations)
  return &clade_annotations_;
}

// -------------------------------------------------------------------

// data

// string newick = 1;
inline void data::clear_newick() {
  newick_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& data::newick() const {
  // @@protoc_insertion_point(field_get:Parsimony.data.newick)
  return newick_.GetNoArena();
}
inline void data::set_newick(const ::std::string& value) {
  
  newick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Parsimony.data.newick)
}
#if LANG_CXX11
inline void data::set_newick(::std::string&& value) {
  
  newick_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Parsimony.data.newick)
}
#endif
inline void data::set_newick(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  newick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Parsimony.data.newick)
}
inline void data::set_newick(const char* value, size_t size) {
  
  newick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Parsimony.data.newick)
}
inline ::std::string* data::mutable_newick() {
  
  // @@protoc_insertion_point(field_mutable:Parsimony.data.newick)
  return newick_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* data::release_newick() {
  // @@protoc_insertion_point(field_release:Parsimony.data.newick)
  
  return newick_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void data::set_allocated_newick(::std::string* newick) {
  if (newick != NULL) {
    
  } else {
    
  }
  newick_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), newick);
  // @@protoc_insertion_point(field_set_allocated:Parsimony.data.newick)
}

// repeated .Parsimony.mutation_list node_mutations = 2;
inline int data::node_mutations_size() const {
  return node_mutations_.size();
}
inline void data::clear_node_mutations() {
  node_mutations_.Clear();
}
inline ::Parsimony::mutation_list* data::mutable_node_mutations(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.data.node_mutations)
  return node_mutations_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parsimony::mutation_list >*
data::mutable_node_mutations() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.data.node_mutations)
  return &node_mutations_;
}
inline const ::Parsimony::mutation_list& data::node_mutations(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.data.node_mutations)
  return node_mutations_.Get(index);
}
inline ::Parsimony::mutation_list* data::add_node_mutations() {
  // @@protoc_insertion_point(field_add:Parsimony.data.node_mutations)
  return node_mutations_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parsimony::mutation_list >&
data::node_mutations() const {
  // @@protoc_insertion_point(field_list:Parsimony.data.node_mutations)
  return node_mutations_;
}

// repeated .Parsimony.condensed_node condensed_nodes = 3;
inline int data::condensed_nodes_size() const {
  return condensed_nodes_.size();
}
inline void data::clear_condensed_nodes() {
  condensed_nodes_.Clear();
}
inline ::Parsimony::condensed_node* data::mutable_condensed_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.data.condensed_nodes)
  return condensed_nodes_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parsimony::condensed_node >*
data::mutable_condensed_nodes() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.data.condensed_nodes)
  return &condensed_nodes_;
}
inline const ::Parsimony::condensed_node& data::condensed_nodes(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.data.condensed_nodes)
  return condensed_nodes_.Get(index);
}
inline ::Parsimony::condensed_node* data::add_condensed_nodes() {
  // @@protoc_insertion_point(field_add:Parsimony.data.condensed_nodes)
  return condensed_nodes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parsimony::condensed_node >&
data::condensed_nodes() const {
  // @@protoc_insertion_point(field_list:Parsimony.data.condensed_nodes)
  return condensed_nodes_;
}

// repeated .Parsimony.node_metadata metadata = 4;
inline int data::metadata_size() const {
  return metadata_.size();
}
inline void data::clear_metadata() {
  metadata_.Clear();
}
inline ::Parsimony::node_metadata* data::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:Parsimony.data.metadata)
  return metadata_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parsimony::node_metadata >*
data::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:Parsimony.data.metadata)
  return &metadata_;
}
inline const ::Parsimony::node_metadata& data::metadata(int index) const {
  // @@protoc_insertion_point(field_get:Parsimony.data.metadata)
  return metadata_.Get(index);
}
inline ::Parsimony::node_metadata* data::add_metadata() {
  // @@protoc_insertion_point(field_add:Parsimony.data.metadata)
  return metadata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parsimony::node_metadata >&
data::metadata() const {
  // @@protoc_insertion_point(field_list:Parsimony.data.metadata)
  return metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Parsimony

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_parsimony_2eproto
