name: Build UShER Port

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Pull latest tree
      run: |
        wget ${{ secrets.GLOBAL_TREE_PATH }}
        ls .github
      
    - name: Checkout ShUShER
      uses: actions/checkout@v2

    - name: Parse UShER Version
      run: echo "USHER_VERSION=$(cat ./usher_version.txt)" >> $GITHUB_ENV
      
    - name: Checkout UShER 
      uses: actions/checkout@v2
      with:
        repository: yatisht/usher
        ref: ${{ env.USHER_VERSION }}
        path: usher
        

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v10

    - name: Compile UShER (C++)
      working-directory: usher
      run: sudo ./installUbuntu.sh
      
    - name: Compile UShER (WebAssembly)
      working-directory: usher-port
      run: |
        sudo apt-get update
        sudo apt-get install wget python3 build-essential cmake protobuf-compiler dh-autoreconf
        ./installUbuntuWeb.sh
        
