# This workflow creates a new tagged WebAssembly/JS bundle and releases it

name: Tag UShER Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, e.g. v0.1.1'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare bundle
        working-directory: usher-port
        run: |
          mkdir usher-port-bundle-${{ github.event.inputs.version }}
          sudo apt-get update
          sudo apt-get install wget python3 build-essential cmake protobuf-compiler dh-autoreconf
          ./installUbuntuWeb.sh
          cp build/usher.* usher-port-bundle-${{ github.event.inputs.version }}
          cd usher-port-bundle-${{ github.event.inputs.version }}
          tar cvzf ../usher-port-bundle-${{ github.event.inputs.version }}.tar.gz *
          
      - name: Release bundle
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: ShUShER ${{ github.event.inputs.version }}
          files: usher-port/usher-port-bundle-${{ github.event.inputs.version }}.tar.gz
