# This workflow creates a new tagged WebAssembly/JS bundle and releases it

name: Tag UShER Bundle

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, e.g. v0.1.1'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare bundle
        run: |
          mkdir usher-port-bundle-${{ github.event.inputs.version }}
          cp usher-port/build/usher.* usher-port-bundle-${{ github.event.inputs.version }}
          cd usher-port-bundle-${{ github.event.inputs.version }}
          tar cvzf ../usher-port-bundle-${{ github.event.inputs.version }}.tar.gz *
          
      - name: Release bundle
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          title: ShUShER ${{ github.event.inputs.version }}
          files: usher-port-bundle-${{ github.event.inputs.version }}.tar.gz
